plugin {
    split-monitor-workspaces {
        count = 5                     # 每個螢幕獨立 5 個
        enable_persistent_workspaces = 1  # 保持 workspace 不消失
        enable_wrapping = 0            # 切到最後一個可回到第一個
        link_monitors = 0              # 獨立切換（千萬別改成 1）
        keep_focused = 1               # 重載後保留目前 focus
    }
}
