# 預先載入圖片（必須先 preload 才能使用）
preload = /home/keye/.config/hypr/wallpaper.jpg

# 設定桌布 (格式為：螢幕代號, 圖片路徑)
# 如果留空螢幕代號 (,,)，則適用於所有螢幕
wallpaper = ,/home/keye/.config/hypr/wallpaper.jpg

# 關閉 IPC 可以省電 (如果你不需要動態切換桌布的話設為 off，否則設為 on)
ipc = on
